### ISSUE TITLE
服务器后台文件IO时崩溃

### ISSUE THREAD

**Issue by tsingyayin** [WeaveStudio-of-UYXA/TianyuServer#1]
服务器由于未知原因崩溃，相关崩溃报错呈现如下。
摘要：*Dav7d_Liang* 随机传送到资源主世界后一分钟，由于游戏未能正确读取`.\s_world\poi\r.-2.1.mca`文件导致崩溃。该文件在服务器上实际不存在。重启服务器后手动传送到该文件负责区域未能复现崩溃。

*由于该世界由`Multiverse-Core`生成，所以暂时认定和`Multiverse-Core`有关。

报错日志
===

[20:07:31] [Server thread/INFO]: Dav7d_Liang issued server command: /rtp world s_world
[20:07:31] [Server thread/WARN]: [BetterRTP] UseLocationIfAvailable is set to `true`, but no location was found for Dav7d_Liang! Using world defaults!
[20:07:41] [Server thread/INFO]: Dav7d_Liang issued server command: /fly
[20:08:11] [Server thread/INFO]: XIUYE114514 issued server command: /e
[20:08:13] [Server thread/INFO]: XIUYE114514 issued server command: /em
[20:08:14] [Server thread/INFO]: XIUYE114514 issued server command: /res tp spawn.chenxi.tree
[20:08:36] [Server thread/INFO]: XIUYE114514 issued server command: /back
[20:08:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: java.nio.file.AccessDeniedException: .\s_world\poi\r.-2.1.mca
	at net.minecraft.server.level.ServerLevel$1.computeForRegionFile(ServerLevel.java:347) ~[?:?]
	at com.destroystokyo.paper.io.PaperFileIOThread.lambda$scheduleRead$5(PaperFileIOThread.java:344) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.destroystokyo.paper.io.PaperFileIOThread.scheduleRead(PaperFileIOThread.java:340) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at com.destroystokyo.paper.io.PaperFileIOThread.loadChunkDataAsync(PaperFileIOThread.java:289) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at com.destroystokyo.paper.io.chunk.ChunkTaskManager.lambda$scheduleChunkLoad$8(ChunkTaskManager.java:377) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkTaskManager.scheduleChunkLoad(ChunkTaskManager.java:365) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkMap.scheduleChunkLoad(ChunkMap.java:1221) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1139) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:452) ~[?:?]
	at net.minecraft.server.level.ChunkMap.getChunkRangeFuture(ChunkMap.java:748) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkMap.prepareAccessibleChunk(ChunkMap.java:1465) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:634) ~[?:?]
	at net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:246) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:831) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1292) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:824) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1375) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1335) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1223) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.AccessDeniedException: .\s_world\poi\r.-2.1.mca
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:298) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:357) ~[?:?]
	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:459) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:432) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.getRegionFile(RegionFileStorage.java:101) ~[?:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.getRegionFile(RegionFileStorage.java:76) ~[?:?]
	at net.minecraft.server.level.ServerLevel$1.computeForRegionFile(ServerLevel.java:345) ~[?:?]
	... 40 more

**Comment by tsingyayin** [comment]
本问题现在在Gitee上追踪
[单击跳转到Gitee](https://gitee.com/tianyu_studio/tianyu-server/issues/I5PIK9)
